export declare const VERSION = "0.1.2";
export declare const DEFAULT_LIMIT = 50;
export declare const DEFAULT_POLLING_INTERVAL = 10000;
export declare const DEFAULT_POST_INTERVAL = 1000;
export declare const DEFAULT_QUERY_INTERVAL = 100;
export declare const DEFAULT_UPDATE_INTERVAL = 100;
export declare const GETALL_LIMIT = 100;
export declare const GETALL_SLEEP_INTERVAL = 100;
export declare const GETALL_LOOP_LIMIT = 1000;
export declare const DEFAULT_MAX_REPLIES_INTERVAL: number;
export declare const DEFAULT_MAX_REPLIES_PER_INTERVAL = 10;
