"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BskyBot = exports.Events = exports.isUserIdentifier = exports.isPostReference = exports.isReplyPost = exports.isPost = exports.isUser = exports.isUri = exports.isCid = exports.isHandle = exports.isDid = void 0;
var types_1 = require("./types");
Object.defineProperty(exports, "isDid", { enumerable: true, get: function () { return types_1.isDid; } });
Object.defineProperty(exports, "isHandle", { enumerable: true, get: function () { return types_1.isHandle; } });
Object.defineProperty(exports, "isCid", { enumerable: true, get: function () { return types_1.isCid; } });
Object.defineProperty(exports, "isUri", { enumerable: true, get: function () { return types_1.isUri; } });
Object.defineProperty(exports, "isUser", { enumerable: true, get: function () { return types_1.isUser; } });
Object.defineProperty(exports, "isPost", { enumerable: true, get: function () { return types_1.isPost; } });
Object.defineProperty(exports, "isReplyPost", { enumerable: true, get: function () { return types_1.isReplyPost; } });
Object.defineProperty(exports, "isPostReference", { enumerable: true, get: function () { return types_1.isPostReference; } });
Object.defineProperty(exports, "isUserIdentifier", { enumerable: true, get: function () { return types_1.isUserIdentifier; } });
Object.defineProperty(exports, "Events", { enumerable: true, get: function () { return types_1.Events; } });
var bot_1 = require("./bot");
Object.defineProperty(exports, "BskyBot", { enumerable: true, get: function () { return bot_1.BskyBot; } });
